### ISSUE TITLE
TestBasicKLAYTransferRecovery fails occationally

### ISSUE THREAD

**Issue by winnie-byun** [klaytn/klaytn#1224] opened 2022-03-07 04:32 UTC
**Describe the bug**
TestBasicKLAYTransferRecovery fails occationally.

**How to reproduce**
I added the following code in `klaytn/node/sc` and run it.
```
for (( i=1; i<=100; i++))
do
  go clean -testcache
  go test -run=TestBasicKLAYTransferRecovery &> makeTest$i.log
done
```

**Expected behavior**
The test should always succeed.

**Attachments**
The error log :
```
go: downloading github.com/gin-gonic/gin v1.7.0
go: downloading github.com/go-playground/validator/v10 v10.4.1
# gopkg.in/olebedev/go-duktape.v3
In file included from _cgo_export.c:4:
debugger.go:23:13: warning: unused function '_duk_debugger_attach' [-Wunused-function]
Created :  /var/folders/sp/vvcsqwwd6q52486gn74n59240000gn/T/sc965653507/parent_bridge_account/0x897716cdcF25F8F8daD06343b281F45D98A69CDe
Created :  /var/folders/sp/vvcsqwwd6q52486gn74n59240000gn/T/sc965653507/child_bridge_account/0xaFDbD13010D08e9f8E181a685801e4282c09A4E3
--- FAIL: TestBasicKLAYTransferRecovery (5.69s)
    vt_recovery_test.go:807: request value transfer nonce 0
    vt_recovery_test.go:829: handle value transfer nonce 0
    vt_recovery_test.go:807: request value transfer nonce 1
    vt_recovery_test.go:829: handle value transfer nonce 1
    vt_recovery_test.go:807: request value transfer nonce 2
    vt_recovery_test.go:829: handle value transfer nonce 2
    vt_recovery_test.go:807: request value transfer nonce 3
    vt_recovery_test.go:829: handle value transfer nonce 3
    vt_recovery_test.go:807: request value transfer nonce 4
    vt_recovery_test.go:809: missing handle value transfer nonce 4
    vt_recovery_test.go:807: request value transfer nonce 5
    vt_recovery_test.go:809: missing handle value transfer nonce 5
    vt_recovery_test.go:807: request value transfer nonce 6
    vt_recovery_test.go:809: missing handle value transfer nonce 6
    bridge_manager_test.go:59: start to wait group
    bridge_manager_test.go:62: waiting group is done
    vt_recovery_test.go:126: value transfer hint &{34 7 4 4 true}
    vt_recovery_test.go:137: check pending tx len 3
    vt_recovery_test.go:164: 
        	Error Trace:	vt_recovery_test.go:164
        	Error:      	Not equal: 
        	            	expected: 0
        	            	actual  : 3
        	Test:       	TestBasicKLAYTransferRecovery
FAIL
exit status 1
FAIL	github.com/klaytn/klaytn/node/sc	6.175s
```

**Comment by hyunsooda** [comment] 2022-08-23 05:36
I could not reproduce the same error with even more tries than the times the author suggests. Also, I couldn't find the possible same error path in around the code logically. A specific context seems to be needed to figure out in detail, but it's not expected to interact with the author. So, let me close it for now.

**Closed by hyunsooda** 2022-08-23 05:36 UTC
