### ISSUE TITLE
QA for v1.10.0 (Kore)

### ISSUE THREAD

**Issue by kjhman21** [klaytn/klaytn#1676] opened 2022-11-09 00:19 UTC
New Features (hardfork)
- KIP-81 Governance @ian0371  
  - #1375
  - #1615 
  - [x] https://github.com/klaytn/klaytn/issues/1676#issuecomment-1316403485
- KIP-82 Reward @blukat29 
  - #1654 
  - #1657
  - [x] https://github.com/klaytn/klaytn/issues/1676#issuecomment-1317975853
- #1687 @blukat29 
  - [x] https://github.com/klaytn/klaytn/issues/1676#issuecomment-1313120578
- #1663 @jiseongnoh 
  - [x] https://github.com/klaytn/klaytn/issues/1676#issuecomment-1314608788
- #1664 @jiseongnoh 
  - [x] https://github.com/klaytn/klaytn/issues/1676#issuecomment-1314608788
- EVM changes @kjeom 
  - #1686
  - #1677
  - [x] https://github.com/klaytn/klaytn/issues/1676#issuecomment-1319359133
- Kore Hardfork config @blukat29 
	- #1639 
	- #1640
	- #1668 
	- [x] https://github.com/klaytn/klaytn/issues/1676#issuecomment-1313124892

Improvements
- #1111 @kjeom 
  - no need to make test cases. It can be covered by regular QA tests.
- #1387 
  - No need to make test cases
- #1673 @ethan-kr 
  - [x] QA: ~It is disabled when mining/validation is running~ effect of data generation in terms of resource usage
  - [x] QA: how many ENs can be supported by a PN with snapshot sync, cypress data
- #1701 @ethan-kr 
  - [x] check three commands of subcommand snapshot.
- #1672 @2dvorak 
  - [x] https://github.com/klaytn/klaytn/issues/1676#issuecomment-1316106070 
- #1670 @kjeom 
  - [x] https://github.com/klaytn/klaytn/issues/1676#issuecomment-1317967264
- #1302 @ethan-kr 
  - [x] check block group is updated as expected
  - [x] check that round and originProposer are added
- Memory consumption reduction @kjeom 
  - #1216
  - #1136
  - No need to test

Fixes
- getLogs API @kjeom 
  - #1653 
  - #1710
  - [x] https://github.com/klaytn/klaytn/issues/1676#issuecomment-1323963767
- #1635 
  - No need to make test cases
- #1445 
  - No need to make test cases
- #1658 @ethan-kr 
  - [x] 10MB message can be sent well
  - [x] a message more than 12 MB is failed to send
- #1431 @ethan-kr 
  - [x] check if backuphash is working after removing recent block
- #1206
  - No need to make test cases
- #1707
  - No need to make test cases 

Miscellaneous
- #1636
  - No need to make test cases
- #1608
  - No need to make test cases
- #1605 @kjeom 
  - [x] https://github.com/klaytn/klaytn/issues/1676#issuecomment-1338493055
- #1594 
- #1616 @2dvorak 
  - [x] https://github.com/klaytn/klaytn/issues/1676#issuecomment-1316110627 
- #1682
- #1548
- #1697
- #1587 
- #1683 @2dvorak  
  - [x] https://github.com/klaytn/klaytn/issues/1676#issuecomment-1316110627

v1.10.0-rc.3 Fixes

- #1722 @2dvorak 
  - [x] check API
- #1723
- #1724 @ian0371 
  - [x] check API
- #1725
- #1726 @blukat29 
  - [x] check API
- #1727 @blukat29 
  - [x] check API
- #1728 #1729 @blukat29
  - [x] Check parameter update timing
- #1730

v1.10.0-rc.4 Fixes

- #1731 @blukat29 
  - [x] https://github.com/klaytn/klaytn/issues/1676#issuecomment-1352762508
- #1734 @blukat29 
  - [x] check homi output
- #1735

v1.10.0-rc.5 Fixes

- #1736
- #1737 @blukat29 
  - [x] check API
- #1738
- #1739 @blukat29 
  - [x] check API
- #1741
- #1742
- #1744

Regular Test Cases @kjeom 

- [x] https://github.com/klaytn/klaytn/issues/1676#issuecomment-1314623575

Consideration @kjeom 
 - caver update to support
   - reward API support
   - governance_chainConfig
 - Refer to https://github.com/klaytn/klaytn/issues/1463 for examples

**Comment by blukat29** [comment] 2022-11-14 05:32
Change DeriveSha tests

- [ ] Inspect block header for TxRoot and ReceiptRoot values, with empty and nonempty TXs
  - [ ] Kore = 0, Genesis.DSha = 0
  - [ ] Kore = 0, Genesis.DSha = 2
  - [ ] Kore = N, Genesis.DSha = 0
  - [ ] Kore = N, Genesis.DSha = 2
  - [ ] Vote = N, Genesis.DSha = 2, Gov.DSha = 0
- [ ] Block sync around DSha-changing block, with empty and nonempty TXs
  - Leading node (Latest.DSha = 0) -> Lagging node (Latest.DSha = 2)

**Comment by blukat29** [comment] 2022-11-14 05:40
Kore Hardfork number tests

- [ ] Homi recognizes `--kore-compatible-blocknumber` flag
  - [ ] genesis.json (local output)
  - [ ] docker-compose.yaml (docker output)
- [ ] Node startup log contains the correct number

**Comment by mckim19** [comment] 2022-11-15 00:54
Even proposer selection tests
- [ ] probability check
  - [ ] changing staking amount
  - [ ] removing validators
  - [ ] adding validators
  - [ ] increasing/decreasing committee size
  - [ ] proposers size check

**Comment by JayChoi1736** [comment] 2022-11-15 01:14
**Regular QA Test**
- [ ] Sync test 

- [ ] Load test 
  - [ ] Stress: 10000 RPS load test for 30m
    - TC: transferSignedTx
    - CN : c6.x8large

  - [ ] Reliability: 2000 RPS load test for 72h 
   - TC: transferSignedTx, newValueTransferTC, newFeeDelegatedSmartContractExecutionTC


- [ ] Rolling Update test: 

- [ ] RPC/WS test: 

- [ ] Governance test: 

- [ ] Reward test: 


- [ ] Caver js/java test: 




- [ ] API performance test: **PASS**
 - TC : readBlockNumber, readGetAccount, readGetBlockByNumber, readGetBlockWithConsensusInfoByNumber
 - EN : m6i.4xlarge * 1

**Comment by 2dvorak** [comment] 2022-11-16 00:53
Debug API tests

- [ ] test if unsafe APIs are only accessible via IPC, not RPC
- [ ] test if debug APIs can be RPC-enabled via flag
- [ ] test if JS-based tracing is disabled in debug APIs
- [ ] test if patched traceBlockFromFile generates same errors whether the file exists or not

**Comment by 2dvorak** [comment] 2022-11-16 00:57
Misc tests
- [ ] test if homi allocates enough balance with `--servicechain` parameter
- [ ] test if TLS certificates work fine with klaytn docker image

**Comment by ian0371** [comment] 2022-11-16 05:52
KIP81 tests

Governance
- [ ] check default governance parameters for GovParamContract
- [ ] check if `governance.vote()` for GovParamContract succeeds
- [ ] check an error when voting GovParamContract with an invalid format

ContractEngine
- [ ]  check if contract parameters are prioritized over header governance
    - [ ]  check `governance.vote()` does not affect governance.itemsAt() for parameters in GovParam
- [ ]  check if ContractEngine does not panic when GovParam is faulty
    - [ ]  GovParam contains a different length of names and params
    - [ ]  GovParam reverts

**Comment by kjeom** [comment] 2022-11-17 00:57
Yaml configuration test

Homi

- [ ] test whether the files(genesis.json, keys, etc) needed to run each networks are created well.

Node

- [ ] test booting each nodes (kcn, kpn, ken, kbn, kscn, kspn, ksen) with yaml file for the each nodes.
- [ ] test every command (help, dumpconfig, init, account, etc) in each binaries

**Comment by ian0371** [comment] 2022-11-17 02:36
KIP82 tests
- [ ] check if rewardee's balance increases as expected when deferredTxFee=true
- [ ] check if rewardee's balance increases as expected when deferredTxFee=false
- [ ] check if `klay_getRewards()` works

**Comment by yoomee1313** [comment] 2022-11-17 23:49
Warm&Cold GasCost tests
how?
* deploy contract and check estimateGas & call & sendTransaction gas cost
* check warm and cold gas costs
[ ] check sload(0x54) gas cost changes
[ ] check call(0xf1, f2, f4, fa) gas cost changes
[ ] check balance(0x31) gas cost changes
[ ] check ext(0x3b, 0x3c, 0x3f) gas cost changes
[ ] check sstore gas cost
[ ] check selfdestruct gas cost

refund gascost change
[ ] check refund gas cost change

modexp gas cost change
[ ] check modexp(0x05) precompiled contract gas cost change

0xef
[ ] check 0xef is reverted by sendTransaction
[ ] check 0xef is reverted by create klaytn transaction type
[ ] check 0xef is reverted in create opcode

**Comment by kjeom** [comment] 2022-11-22 16:44
getLogs API tests
- [ ] check logs returned by blockHash filtered API
- [ ] check logs returned by block number range filtered API
- [ ] check corner cases (null, negative range, invalid blockHash, etc...)

**Comment by kjeom** [comment] 2022-12-06 00:40
Key generation test by homi
- [ ] check if keystore and reward file are created as intended in various generation types (cypress, baobab, ..)
- [ ] check if the local networks with the keys are working with no any problem

**Comment by blukat29** [comment] 2022-12-15 08:53
v1.10.0-rc.3 Fixes

- #1722 @2dvorak 
  - [x] check API
- #1723
- #1724 @ian0371 
  - [x] check API
- #1725
- #1726 @blukat29 
  - [x] check API
- #1727 @blukat29 
  - [x] check API
- #1728 #1729 @blukat29
  - [x] Check parameter update timing
- #1730

**Comment by blukat29** [comment] 2022-12-15 09:13
API aliases test

- [ ] governance_chainConfig = klay_chainConfig
- [ ] governance_chainConfigAt = klay_chainConfigAt
- [ ] governance_nodeAddress = klay_nodeAddress
- [ ] governance_itemsAt = klay_govParamsAt
- [ ] governance_getStakingInfo = klay_getStakingInfo

**Comment by JayChoi1736** [comment] 2022-12-21 00:11
**Regular QA Test**

v1.10.0-rc.5

- [x] Rolling Update test:  **PASS**
  - before kore hardfork
  - [rolling.log](https://github.com/klaytn/klaytn/files/10273475/rolling.log)

- [x] RPC/WS test: **PASS**
  - [rpc result](https://github.com/klaytn/klaytn/files/10273481/klaytn.log)
  - [ws result](https://github.com/klaytn/klaytn/files/10273483/klaytn.log)

- [x] Governance test: **PASS** 
   - [governance.log](https://github.com/klaytn/klaytn/files/10273479/governance.log)

- [x] Reward test:  **PASS**
  - [reward.log](https://github.com/klaytn/klaytn/files/10102815/reward.log)

**Comment by kjhman21** [comment] 2022-12-25 22:41
@JayChoi1736 @yoomee1313 
Doesn't we need to have compatibility test with Popular Ethereum tools (Metamask, remix, etc.)?

**Comment by ian0371** [comment] 2022-12-26 01:38
Ethereum tools convenience
- [ ] MetaMask
- [ ] web3.js
- [ ] ethers.js
- [ ] truffle
- [ ] hardhat

**Comment by aidan-kwon** [comment] 2022-12-28 03:15
All QA tasks are successfully done and v1.10.0 has been released. 
Close this issue.

**Closed by aidan-kwon** 2022-12-28 03:15 UTC
