### ISSUE TITLE
segmentation fault while running the endpoint node

### ISSUE THREAD

**Issue by buggycode** [klaytn/klaytn#1108] opened 2022-01-10 02:46 UTC
**Describe the bug**
I'm facing segmentation fault while running the endpoint node. Two times with the binary downloaded from the packages.klaytn.net. And again with the binary I compiled from the machine with tag/v1.7.3 and go1.16.12. 

**How to reproduce**
run `ken` again with `kend start`. wait a while to show the error.

**Expected behavior**
No SIGSEGV

**Attachments**
[kend.out.log](https://github.com/klaytn/klaytn/files/7836590/kend.out.log)
logs from the `kend.out`
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12af8b0]

goroutine 384572 [running]:
github.com/klaytn/klaytn/blockchain/types.(*Block).Root(...)
        /home/yyk/codes/klaytn/blockchain/types/block.go:284
github.com/klaytn/klaytn/blockchain.(*BlockChain).insertChain.func1(0x0, 0xc000181900, 0xc04e6851f0, 0xc0885f3d28, 0xc06f047ebb58eb76, 0x825a0bad34, 0x2f429c0)
        /home/yyk/codes/klaytn/blockchain/blockchain.go:1642 +0x50
created by github.com/klaytn/klaytn/blockchain.(*BlockChain).insertChain
        /home/yyk/codes/klaytn/blockchain/blockchain.go:1641 +0x1299
```

**Environment (please complete the following information)**
 - Klaytn version : `Klaytn v1.7.3`
 - go version `go1.16.12`
 - OS and its version `Rocky Linux 8.5`

**Additional context**

**Comment by buggycode** [comment] 2022-01-10 05:15
I need to check memory, but all errors are pointed to the same location. 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12af8b0]

goroutine 847343 [running]:
github.com/klaytn/klaytn/blockchain/types.(*Block).Root(...)
	/home/yyk/codes/klaytn/blockchain/types/block.go:284
github.com/klaytn/klaytn/blockchain.(*BlockChain).insertChain.func1(0x0, 0xc000181900, 0xc0774e4e70, 0xc09e7616f8, 0xc06f06d8f86a585a, 0x188ef5ec7e3, 0x2f429c0)
	/home/yyk/codes/klaytn/blockchain/blockchain.go:1642 +0x50
created by github.com/klaytn/klaytn/blockchain.(*BlockChain).insertChain
	/home/yyk/codes/klaytn/blockchain/blockchain.go:1641 +0x1299
```

**Comment by aidan-kwon** [comment] 2022-01-12 00:47
@hqjang-pepper Could you take a look?

**Comment by hqjang-pepper** [comment] 2022-01-12 01:41
Hi. May I ask you some more detail information about your node configuration?
1. network : cypress or baobab?
2. ken version : Was v1.7.3 your one and only ken version, or upgraded from previous version? (ex. 1.6.0 -> 1.7.3) 
3. gentle stop and start : Did you execute `kend stop` before you run ken again with `kend start`?

+ This problem might be caused by race condition in blockchain.go, with high possibility.
https://github.com/klaytn/klaytn/pull/1099
Currently we are working on to fix this race condition problem. 
If new version is released with this PR merged, try it again. I'll inform you.
Thank you.

**Comment by buggycode** [comment] 2022-01-12 03:43
1. cypress
2. I only used v1.7.3
3. it got segmentation fault so not gracefully restarted.

Thank you for the related issue.

**Closed** 2022-07-08 04:24 UTC
