### ISSUE TITLE
clearly separate roles of ValidateSender, ValidateMutableValues, ValidateFeePayer, SigValidationGas

### ISSUE THREAD

**Issue by ehnuje** [klaytn/klaytn#1153] opened 2022-02-09 09:51 UTC
After taking a look into 4 functions(ValidateSender, ValidateMutableValues, ValidateFeePayer, SigValidationGas), I found that they do somethings common and sometimes they do what is not expected to be done based on their names. 

**Bolded ones** are the ones that I expect to be done in each function.

- `ValidateSender` checks..
  - **sender’s account key**
  - gas required to validate a tx (by SigValidationGas)
- `ValidateMutableValue` checks..
  - sender’s account key
  - fee payer’s account key
  - **mutable values by tx types**
- `ValidateFeePayer` checks..
  - **fee payer’s account key**
  - gas required to validate a tx (by SigValidationGas)
- `SigValidationGas` checks..
  - **gas required to validate a tx**

I have some questions before clearing this.
1. Is there any reason why do `ValidateSender` and `ValidateFeePayer` check gas by calling SigValidationGas?
2. Is there any reason why do `ValidateMutableValue` check sender and fee payer's account key instead of calling `ValidateSender` and `ValidateFeePayer` at  `txList.Filter`, the only place `ValidateMutableValue` is called?

**Comment by ehnuje** [comment] 2022-02-09 09:51
cc @winnie-byun

**Comment by ehnuje** [comment] 2022-02-09 09:58
> 1. Is there any reason why do ValidateSender and ValidateFeePayer check gas by calling SigValidationGas?

It seems that `SigValidationGas` is called before account validation to avoid expensive signature validation.

**Comment by winnie-byun** [comment] 2022-02-10 00:11
@ehnuje To add, `ValidateSender` also looks for and fills in `validatedSender` and `validatedFeePayer`.
Depending on the transaction type, `from` address could be in either at `transaction.from` or `transaction.data.From`.  `ValidateSender` finds the address from either place.

**Comment by kjhman21** [comment] 2022-02-11 06:22
> 1. Is there any reason why do ValidateSender and ValidateFeePayer check gas by calling SigValidationGas?

As you said gas cost caused by key validation is calculated in that function. And then gas cost is checked at TxPool.validateTx and Transaction.AsMessageWithAccountKeyPicker.

> 2. Is there any reason why do ValidateMutableValue check sender and fee payer's account key instead of calling ValidateSender and ValidateFeePayer at txList.Filter, the only place ValidateMutableValue is called?

txList.Filter is called when we check whether the tx can be dropped or not. So it checks the dynamic values only. It is called every time tx pool is re-iterated.

**Comment by aidan-kwon** [comment] 2022-08-22 07:50
@ehnuje Please, close this issue if you got enough answer

**Closed** 2023-01-04 07:23 UTC
