### ISSUE TITLE
kend bad bock

### ISSUE THREAD

**Issue by tjdwjs23** [klaytn/klaytn#2042] opened 2023-11-21 02:33 UTC
ubuntu 22.04 server

error

INFO[11/21,11:31:54 +09] [48] There is already corresponding badblock in db.  badblock number=126403200
ERROR[11/21,11:31:54 +09] [5] ########## BAD BLOCK ######### Chain config: {ChainID: 8217 IstanbulCompatibleBlock: 86816005 LondonCompatibleBlock: 86816005 EthTxTypeCompatibleBlock: 86816005 MagmaCompatibleBlock: 99841497 KoreCompatibleBlock: 119750400 ShanghaiCompatibleBlock: 135456000 KIP103CompatibleBlock: 119750400 KIP103ContractAddress 0xD5ad6D61Dd87EdabE2332607C328f5cc96aeCB95 SubGroupSize: 31 UnitPrice: 250000000000 DeriveShaImpl: 2 Engine: istanbul} Number: 126403200 Hash: 0x51023737aac50f832f50d7f70678eaaa8359f635649737df63c2eb5ec52ccbe3 Receipt:  Error: Received change mismatches with the value this node has!!
WARN[11/21,11:31:54 +09] [28] Synchronisation failed, dropping peer     peer=0b871735f4ed38d7 err="retrieved hash chain is invalid: Received change mismatches with the value this node has!!"

Current Block: 126403199 is currently stopped and heightBlock: 138560631 is increasing normally.

**Comment by hyunsooda** [comment] 2023-11-21 08:01
Hi @tjdwjs23, Thanks for the reporting. I'd like to request some of recorded logs. Could you provide following further logs?


1. I guess you have an error log which has a prefix `Verification Error: ...`. Could you attach this log?
2. Did you restart that node between the block number `126061533` and `126403199`?
2-1. Could you check out the following log was appeared?
   - Either `No governance state found in a database` or `Successfully loaded governance state from database ...`. 
3. The issue appears uncommon and challenging to replicate. Could you please upload the chaindata for testing?
4. Please let me know the node version you are using. (You can check out via `ken version`)

**Comment by tjdwjs23** [comment] 2023-11-21 08:06
INFO[11/21,17:04:58 +09] [48] There is already corresponding badblock in db.  badblock number=126403200
ERROR[11/21,17:04:58 +09] [5] ########## BAD BLOCK ######### Chain config: {ChainID: 8217 IstanbulCompatibleBlock: 86816005 LondonCompatibleBlock: 86816005 EthTxTypeCompatibleBlock: 86816005 MagmaCompatibleBlock: 99841497 KoreCompatibleBlock: 119750400 ShanghaiCompatibleBlock: 135456000 KIP103CompatibleBlock: 119750400 KIP103ContractAddress 0xD5ad6D61Dd87EdabE2332607C328f5cc96aeCB95 SubGroupSize: 31 UnitPrice: 250000000000 DeriveShaImpl: 2 Engine: istanbul} Number: 126403200 Hash: 0x51023737aac50f832f50d7f70678eaaa8359f635649737df63c2eb5ec52ccbe3 Receipt:  Error: Received change mismatches with the value this node has!!
WARN[11/21,17:04:58 +09] [28] Synchronisation failed, dropping peer     peer=7e009645747937d4                           err="retrieved hash chain is invalid: Received change mismatches with the value this node has!!"
WARN[11/21,17:04:58 +09] [33] ProtocolManager failed to read msg        id=7e009645747937d4 conn=inbound            err=EOF
WARN[11/21,17:04:58 +09] [33] ProtocolManager failed to read msg        id=7e009645747937d4 conn=inbound            err=EOF
INFO[11/21,17:04:58 +09] [33] Disconnected a multichannel P2P Peer      id=7e009645747937d4 conn=inbound            peerID=7e009645747937d4 peerName=Klaytn/v1.11.1/linux-amd64/go1.20.6           err=EOF
INFO[11/21,17:04:58 +09] [33] Added a single channel P2P Peer           id=530b21c0631e915f conn=inbound            peerID=530b21c0631e915f
INFO[11/21,17:04:59 +09] [33] [Dial] Add dial candidate from static nodes  id=56692ae9309f8c07 NodeType=2  ip=15.164.111.88  mainPort=32323 port="[32323 32324]"
INFO[11/21,17:04:59 +09] [33] [Dial] Add dial candidate from static nodes  id=555f6552bcc2b348 NodeType=2  ip=3.38.39.99     mainPort=32323 port="[32323 32324]"
INFO[11/21,17:04:59 +09] [33] Added a multichannel P2P Peer             id=56692ae9309f8c07 conn=trusted-staticdial peerID=56692ae9309f8c07
INFO[11/21,17:04:59 +09] [33] Added a multichannel P2P Peer             id=555f6552bcc2b348 conn=trusted-staticdial peerID=555f6552bcc2b348
INFO[11/21,17:04:59 +09] [33] Added a single channel P2P Peer           id=738605ac0830697f conn=inbound            peerID=738605ac0830697f
INFO[11/21,17:05:00 +09] [33] Added a single channel P2P Peer           id=74631173009b52b4 conn=dyndial            peerID=74631173009b52b4
^[ERROR[11/21,17:05:00 +09] [30] Verification Error                        len(receivedChangeSet)=1 len(changeSet)=0
ERROR[11/21,17:05:00 +09] [30] Verification Error                        key=governance.governingnode received=0xC0cBE1C770fbCE1eb7786BFBa1Ac2115D5C0a456 have=nil receivedType=common.Address haveType=nil


This is the whole log

I was the first to suspect the version, but I

instance: Klaytn/v1.11.1/linux-amd64/go1.20.6

Use the latest version

**Comment by hyunsooda** [comment] 2023-11-21 23:06
When initiating a node, the very important log (2-1) should have recorded either `No governance state found in a database` or `Successfully loaded governance state from database...`. Could you check this out, please? Although the former is expected, its occurrence is uncommon unless the database file is manually deleted. Kindly share the chaindata related to the problematic block for analysis of the issue.

To fix your chain, execute the command **`setHead(126061532)`**. Please enter this on the attached console and confirm if the issue is resolved by typing **`setHead(126061533)`**. This operation is time-consuming.

**Comment by tjdwjs23** [comment] 2023-11-22 05:53
INFO[11/22,14:51:24 +09] [18] Cypress network ID is set                 networkid=8217
INFO[11/22,14:51:24 +09] [18] Set the concurrency limit of RPC-HTTP server  limit=3000
INFO[11/22,14:51:24 +09] [18] Raised fd limit to process's maximum value  fd=524288
INFO[11/22,14:51:24 +09] [18] Cypress network ID is set                 networkid=8217
INFO[11/22,14:51:24 +09] [18] Archiving mode of this node               isArchiveMode=false
INFO[11/22,14:51:24 +09] [40] Ntp time check                            local=2023-11-22T05:51:24.393179523Z remote=2023-11-22T05:51:24.384115366Z
INFO[11/22,14:51:24 +09] [40] Starting peer-to-peer node                instance=Klaytn/v1.11.1/linux-amd64/go1.20.6
INFO[11/22,14:51:24 +09] [48] Non-single database is used for persistent storage  DBType=LevelDB
INFO[11/22,14:51:24 +09] [48] LevelDB configurations                    path=/var/kend/data/klay/chaindata/misc levelDBCacheSize=16 openFilesLimit=5242 useBufferPool=true usePerfCheck=true compressionType=none compactionTableSize(MB)=2 compactionTableSizeMultiplier=1.000
INFO[11/22,14:51:24 +09] [48] LevelDB configurations                    path=/var/kend/data/klay/chaindata/header levelDBCacheSize=38 openFilesLimit=13107 useBufferPool=true usePerfCheck=true compressionType=none compactionTableSize(MB)=2 compactionTableSizeMultiplier=1.000
INFO[11/22,14:51:25 +09] [48] LevelDB configurations                    path=/var/kend/data/klay/chaindata/body   levelDBCacheSize=38 openFilesLimit=13107 useBufferPool=true usePerfCheck=true compressionType=none compactionTableSize(MB)=2 compactionTableSizeMultiplier=1.000
INFO[11/22,14:51:26 +09] [48] LevelDB configurations                    path=/var/kend/data/klay/chaindata/receipts levelDBCacheSize=38 openFilesLimit=13107 useBufferPool=true usePerfCheck=true compressionType=none compactionTableSize(MB)=2 compactionTableSizeMultiplier=1.000
INFO[11/22,14:51:27 +09] [48] LevelDB configurations                    path=/var/kend/data/klay/chaindata/statetrie_migrated_100176913/0 levelDBCacheSize=76 openFilesLimit=26214 useBufferPool=true usePerfCheck=true compressionType=none compactionTableSize(MB)=2 compactionTableSizeMultiplier=1.000
INFO[11/22,14:51:30 +09] [48] LevelDB configurations                    path=/var/kend/data/klay/chaindata/statetrie_migrated_100176913/1 levelDBCacheSize=76 openFilesLimit=26214 useBufferPool=true usePerfCheck=true compressionType=none compactionTableSize(MB)=2 compactionTableSizeMultiplier=1.000
INFO[11/22,14:51:33 +09] [48] LevelDB configurations                    path=/var/kend/data/klay/chaindata/statetrie_migrated_100176913/2 levelDBCacheSize=76 openFilesLimit=26214 useBufferPool=true usePerfCheck=true compressionType=none compactionTableSize(MB)=2 compactionTableSizeMultiplier=1.000
INFO[11/22,14:51:36 +09] [48] LevelDB configurations                    path=/var/kend/data/klay/chaindata/statetrie_migrated_100176913/3 levelDBCacheSize=76 openFilesLimit=26214 useBufferPool=true usePerfCheck=true compressionType=none compactionTableSize(MB)=2 compactionTableSizeMultiplier=1.000
INFO[11/22,14:51:39 +09] [48] Created a sharded database                dbType=statetrie numShards=4
INFO[11/22,14:51:39 +09] [48] LevelDB configurations                    path=/var/kend/data/klay/chaindata/txlookup                       levelDBCacheSize=16 openFilesLimit=5242  useBufferPool=true usePerfCheck=true compressionType=none compactionTableSize(MB)=2 compactionTableSizeMultiplier=1.000
INFO[11/22,14:51:39 +09] [48] LevelDB configurations                    path=/var/kend/data/klay/chaindata/bridgeservice                  levelDBCacheSize=16 openFilesLimit=2621  useBufferPool=true usePerfCheck=true compressionType=none compactionTableSize(MB)=2 compactionTableSizeMultiplier=1.000
INFO[11/22,14:51:39 +09] [48] LevelDB configurations                    path=/var/kend/data/klay/chaindata/snapshot                       levelDBCacheSize=22 openFilesLimit=7864  useBufferPool=true usePerfCheck=true compressionType=none compactionTableSize(MB)=2 compactionTableSizeMultiplier=1.000
INFO[11/22,14:51:39 +09] [30] Successfully loaded governance state from database  blockNumber=135456768
INFO[11/22,14:51:39 +09] [41] Initialised chain configuration           config="{ChainID: 8217 IstanbulCompatibleBlock: 86816005 LondonCompatibleBlock: 86816005 EthTxTypeCompatibleBlock: 86816005 MagmaCompatibleBlock: 99841497 KoreCompatibleBlock: 119750400 ShanghaiCompatibleBlock: 135456000 KIP103CompatibleBlock: 119750400 KIP103ContractAddress 0xD5ad6D61Dd87EdabE2332607C328f5cc96aeCB95 SubGroupSize: 22 UnitPrice: 25000000000 DeriveShaImpl: 2 Engine: istanbul}"
INFO[11/22,14:51:39 +09] [41] Initialising Klaytn protocol              versions="[65 64]" network=8217
INFO[11/22,14:51:39 +09] [49] Initializing local trie node cache (fastCache)  MaxMiB=19278 FilePath=/var/kend/data/fastcache
INFO[11/22,14:51:39 +09] [49] Initialized local trie node cache (fastCache)  LoadedMiB=0 LoadedEntries=0 elapsed=21.01734ms
INFO[11/22,14:51:39 +09] [5] Loaded most recent local header           number=126403199 hash=2191c3…4a8378 td=126403200 age=4mo3w1d
INFO[11/22,14:51:39 +09] [5] Loaded most recent local full block       number=126403199 hash=2191c3…4a8378 td=126403200 age=4mo3w1d
INFO[11/22,14:51:39 +09] [5] Loaded most recent local fast block       number=119750300 hash=cfd829…851f52 td=119750301 age=4mo3w1d
INFO[11/22,14:51:39 +09] [5] prefetchTxWorkers are started             num=32
INFO[11/22,14:51:39 +09] [41] Live pruning is disabled because flag not stored in database
INFO[11/22,14:51:39 +09] [5] InitDeriveSha                             initial=2 withGov=true
INFO[11/22,14:51:40 +09] [5] Loaded local transaction journal          transactions=182 dropped=0
INFO[11/22,14:51:40 +09] [5] Regenerated local transaction journal     transactions=182 accounts=7
INFO[11/22,14:51:40 +09] [40] Starting P2P networking
INFO[11/22,14:51:43 +09] [35] Mapped network port                       protobuf=udp extport=32323 intport=32323 interface="UPNP IGDv2-IP1"
INFO[11/22,14:51:43 +09] [34] UDP listener up                           self="kni://4cf6d72d38eab6924b828ede612971091d06c4b3413672878180c8605d00d15a5c2d82be8b680879f96a68ea99286e93e012d2833f11ddac0679286deeb949f5@210.207.161.2:32323?ntype=en"
INFO[11/22,14:51:43 +09] [40] Started P2P server                        id=4cf6d72d38eab692 multichannel=true
INFO[11/22,14:51:43 +09] [40] RLPx listener up                          self="kni://4cf6d72d38eab6924b828ede612971091d06c4b3413672878180c8605d00d15a5c2d82be8b680879f96a68ea99286e93e012d2833f11ddac0679286deeb949f5@210.207.161.2:32323?ntype=en"
INFO[11/22,14:51:43 +09] [40] RLPx listener up                          self="kni://4cf6d72d38eab6924b828ede612971091d06c4b3413672878180c8605d00d15a5c2d82be8b680879f96a68ea99286e93e012d2833f11ddac0679286deeb949f5@210.207.161.2:32323?ntype=en"
INFO[11/22,14:51:43 +09] [44] Start listening chain head event to update stakingInfoCache.
INFO[11/22,14:51:43 +09] [40] IPC endpoint opened                       url=/var/kend/data/klay.ipc
INFO[11/22,14:51:43 +09] [40] HTTP endpoint opened                      url=http://0.0.0.0:8551     cors=* vhosts=*
INFO[11/22,14:51:43 +09] [40] WebSocket endpoint opened                 url=ws://[::]:8552
INFO[11/22,14:51:43 +09] [35] Mapped network port                       protobuf=tcp extport=32324 intport=32324 interface="UPNP IGDv2-IP1"
INFO[11/22,14:51:43 +09] [35] Mapped network port                       protobuf=tcp extport=32323 intport=32323 interface="UPNP IGDv2-IP1"
INFO[11/22,14:51:46 +09] [33] Added a multichannel P2P Peer             id=732e6834d9d3f860 conn=inbound peerID=732e6834d9d3f860
INFO[11/22,14:51:47 +09] [33] [Dial] Add dial candidate from static nodes  id=301c8d7d8f3b0352 NodeType=2 ip=20.41.113.30 mainPort=32323 port="[32323 32324]"
INFO[11/22,14:51:47 +09] [33] [Dial] Add dial candidate from static nodes  id=612d7a88bad7b987 NodeType=2 ip=3.36.151.126 mainPort=32323 port=[32323]
INFO[11/22,14:51:47 +09] [33] Added a multichannel P2P Peer             id=301c8d7d8f3b0352 conn=trusted-staticdial peerID=301c8d7d8f3b0352
INFO[11/22,14:51:47 +09] [33] Added a multichannel P2P Peer             id=612d7a88bad7b987 conn=trusted-staticdial peerID=612d7a88bad7b987
INFO[11/22,14:51:47 +09] [33] Added a single channel P2P Peer           id=530b21c0631e915f conn=inbound            peerID=530b21c0631e915f
INFO[11/22,14:51:49 +09] [33] Added a multichannel P2P Peer             id=95026b0c683e378c conn=inbound            peerID=95026b0c683e378c
INFO[11/22,14:51:50 +09] [28] Block synchronisation started
INFO[11/22,14:51:50 +09] [51] Mining aborted due to sync
INFO[11/22,14:51:51 +09] [28] Downloader queue stats                    receiptTasks=0 blockTasks=1757 stakingInfoTasks=0 itemSize=2.46kB throttle=8192
ERROR[11/22,14:51:51 +09] [30] Verification Error                        len(receivedChangeSet)=1 len(changeSet)=0
ERROR[11/22,14:51:51 +09] [30] Verification Error                        key=governance.governingnode received=0xC0cBE1C770fbCE1eb7786BFBa1Ac2115D5C0a456 have=nil receivedType=common.Address haveType=nil
INFO[11/22,14:51:51 +09] [48] There is already corresponding badblock in db.  badblock number=126403200
ERROR[11/22,14:51:51 +09] [5] ########## BAD BLOCK ######### Chain config: {ChainID: 8217 IstanbulCompatibleBlock: 86816005 LondonCompatibleBlock: 86816005 EthTxTypeCompatibleBlock: 86816005 MagmaCompatibleBlock: 99841497 KoreCompatibleBlock: 119750400 ShanghaiCompatibleBlock: 135456000 KIP103CompatibleBlock: 119750400 KIP103ContractAddress 0xD5ad6D61Dd87EdabE2332607C328f5cc96aeCB95 SubGroupSize: 31 UnitPrice: 250000000000 DeriveShaImpl: 2 Engine: istanbul} Number: 126403200 Hash: 0x51023737aac50f832f50d7f70678eaaa8359f635649737df63c2eb5ec52ccbe3 Receipt:  Error: Received change mismatches with the value this node has!!
WARN[11/22,14:51:51 +09] [28] Synchronisation failed, dropping peer     peer=301c8d7d8f3b0352 err="retrieved hash chain is invalid: Received change mismatches with the value this node has!!"
WARN[11/22,14:51:51 +09] [33] ProtocolManager failed to read msg        id=301c8d7d8f3b0352 conn=trusted-staticdial err=EOF
WARN[11/22,14:51:51 +09] [33] ProtocolManager failed to read msg        id=301c8d7d8f3b0352 conn=trusted-staticdial err=EOF
INFO[11/22,14:51:51 +09] [33] Disconnected a multichannel P2P Peer      id=301c8d7d8f3b0352 conn=trusted-staticdial peerID=301c8d7d8f3b0352 peerName=Klaytn/v1.11.1/linux-amd64/go1.20.6 err=EOF
ERROR[11/22,14:51:53 +09] [30] Verification Error                        len(receivedChangeSet)=1 len(changeSet)=0
ERROR[11/22,14:51:53 +09] [30] Verification Error                        key=governance.governingnode received=0xC0cBE1C770fbCE1eb7786BFBa1Ac2115D5C0a456 have=nil receivedType=common.Address haveType=nil
INFO[11/22,14:51:53 +09] [48] There is already corresponding badblock in db.  badblock number=126403200
ERROR[11/22,14:51:53 +09] [5] ########## BAD BLOCK ######### Chain config: {ChainID: 8217 IstanbulCompatibleBlock: 86816005 LondonCompatibleBlock: 86816005 EthTxTypeCompatibleBlock: 86816005 MagmaCompatibleBlock: 99841497 KoreCompatibleBlock: 119750400 ShanghaiCompatibleBlock: 135456000 KIP103CompatibleBlock: 119750400 KIP103ContractAddress 0xD5ad6D61Dd87EdabE2332607C328f5cc96aeCB95 SubGroupSize: 31 UnitPrice: 250000000000 DeriveShaImpl: 2 Engine: istanbul} Number: 126403200 Hash: 0x51023737aac50f832f50d7f70678eaaa8359f635649737df63c2eb5ec52ccbe3 Receipt:  Error: Received change mismatches with the value this node has!!
WARN[11/22,14:51:53 +09] [28] Synchronisation failed, dropping peer     peer=732e6834d9d3f860 err="retrieved hash chain is invalid: Received change mismatches with the value this node has!!"
WARN[11/22,14:51:53 +09] [33] ProtocolManager failed to read msg        id=732e6834d9d3f860 conn=inbound            err=EOF
WARN[11/22,14:51:53 +09] [33] ProtocolManager failed to read msg        id=732e6834d9d3f860 conn=inbound            err=EOF
INFO[11/22,14:51:53 +09] [33] Disconnected a multichannel P2P Peer      id=732e6834d9d3f860 conn=inbound            peerID=732e6834d9d3f860 peerName=Klaytn/v1.11.1/linux-amd64/go1.20.6 err=EOF

I am attaching the log again I started and pasted all the logs

I tried to execute the setHead command you said

Welcome to the Klaytn JavaScript console!

instance: Klaytn/v1.11.1/linux-amd64/go1.20.6
 datadir: /var/kend/data
 modules: admin:1.0 debug:1.0 eth:1.0 governance:1.0 istanbul:1.0 klay:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

> setHead(126061532)
ReferenceError: 'setHead' is not defined
    at <anonymous>:1:1

**Comment by yoomee1313** [comment] 2023-11-22 07:05
Could you share how this error occured? Normally, this kind of error occurs when governance data is polluted. Have you done or experienced any of below activities?
* rewinding: used --start-block-num or setHead
* unexpected node termination
* or just restarting node

Also, you can go back to specific block and re-sync again with `--start-block-num` flag. `setHead` can pollute governance data with v1.11.1 or under. Btw, we put a setHead fix recently, and it will be put in v1.12.0.

You can configure --start-block-num in ADDITIONAL field of kend.conf. We recommend rewinding to the block before 126061532 because a vote which changes governingnode has been done at 126061533. Below is an example kend.conf.
```
ADDITIONAL="--start-block-num 126060544  $ADDITIONAL"
```

**Comment by yoomee1313** [comment] 2024-04-03 08:05
Close this issue since no more activity. If problem occurs again, please reopen this issue with additional information.

**Closed by yoomee1313** 2024-04-03 08:05 UTC
Labels: Github
