### ISSUE TITLE
Ken panic during syncing

### ISSUE THREAD

**Issue by Jongsic** [klaytn/klaytn#432] opened 2020-01-02 02:17 UTC
```
INFO[12/31,11:05:09 Z] [5] Imported new chain segment                number=16322964 hash=b6a8c7…874fcd blocks=1   txs=0   elapsed=10.655ms      trieDBSize=1.13mB   mgas=0.000  mgasps=0.000
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x8f5016]

goroutine 6447039 [running]:
github.com/klaytn/klaytn/blockchain/types.(*Transaction).ValidatedSender(0x0, 0x0, 0x0, 0xc000000000)
        /ext-go/1/src/github.com/klaytn/klaytn/blockchain/types/transaction.go:225 +0x16
github.com/klaytn/klaytn/blockchain.NewEVMContext(0x1645500, 0x0, 0xc10d6aab40, 0x161ab20, 0xc001832000, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /ext-go/1/src/github.com/klaytn/klaytn/blockchain/evm.go:54 +0xe5
github.com/klaytn/klaytn/node/cn.(*PrivateDebugAPI).traceBlock.func1(0xc15622e540, 0xc0df45dd40, 0xc0c0b30680, 0x19, 0x19, 0x163ad20, 0xc0f69ecff0, 0xc0e9456e70, 0xc010957440, 0x1630d60, ...)
        /ext-go/1/src/github.com/klaytn/klaytn/node/cn/api_tracer.go:483 +0x1d7
created by github.com/klaytn/klaytn/node/cn.(*PrivateDebugAPI).traceBlock
        /ext-go/1/src/github.com/klaytn/klaytn/node/cn/api_tracer.go:477 +0x45e
```

```
INFO[12/31,23:52:47 Z] [5] Imported new chain segment                number=16369022 hash=238a9f…1db20e blocks=1  txs=4   elapsed=29.954ms     trieDBSize=5.76mB   mgas=0.051   mgasps=1.712    ignored=1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x8f5016]

goroutine 2081661 [running]:
github.com/klaytn/klaytn/blockchain/types.(*Transaction).ValidatedSender(0x0, 0x0, 0x0, 0xc100000000)
        /ext-go/1/src/github.com/klaytn/klaytn/blockchain/types/transaction.go:225 +0x16
github.com/klaytn/klaytn/blockchain.NewEVMContext(0x1645500, 0x0, 0xc01ab42fc0, 0x161ab20, 0xc000a3c000, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /ext-go/1/src/github.com/klaytn/klaytn/blockchain/evm.go:54 +0xe5
github.com/klaytn/klaytn/node/cn.(*PrivateDebugAPI).traceBlock.func1(0xc111ddb900, 0xc0c16152c0, 0xc019682120, 0x23, 0x23, 0x163ad20, 0xc12485e970, 0xc0fd42a1c0, 0xc0014994f0, 0x1630d60, ...)
        /ext-go/1/src/github.com/klaytn/klaytn/node/cn/api_tracer.go:483 +0x1d7
created by github.com/klaytn/klaytn/node/cn.(*PrivateDebugAPI).traceBlock
        /ext-go/1/src/github.com/klaytn/klaytn/node/cn/api_tracer.go:477 +0x45e
```

**Environment (please complete the following information)**

* AWS Ubuntu 18.04 & m5.2xlarge

```
$ ken version
Klaytn v1.3.0
```

**Additional context**

ken node started by using "klaytn-cypress-chaindata-20191227011212.tar.gz"

**Comment by nogang** [comment] 2020-01-02 04:30
Can you tell me API and parameters you used to call? @Jongsic

**Comment by Jongsic** [comment] 2020-01-03 08:21
I call below APIs for every block

* getBlock
* getPastLogs
* getBlockReceipts
* debug_traceBlockByNumber - {tracer: "callTracer"}

**Comment by Jongsic** [comment] 2020-01-07 09:00
error occurs again

```INFO[01/07,08:59:18 Z] [5] Imported new chain segment                number=16920098 hash=d9ee34…b16724 blocks=1   txs=2   elapsed=128.204ms    trieDBSize=2.55mB   mgas=0.868  mgasps=6.772
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x8f5016]

goroutine 1708042 [running]:
github.com/klaytn/klaytn/blockchain/types.(*Transaction).ValidatedSender(0x0, 0x0, 0x0, 0xc100000000)
        /ext-go/1/src/github.com/klaytn/klaytn/blockchain/types/transaction.go:225 +0x16
github.com/klaytn/klaytn/blockchain.NewEVMContext(0x1645500, 0x0, 0xc145a06480, 0x161ab20, 0xc0011be800, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /ext-go/1/src/github.com/klaytn/klaytn/blockchain/evm.go:54 +0xe5
github.com/klaytn/klaytn/node/cn.(*PrivateDebugAPI).traceBlock.func1(0xc0c5d278c0, 0xc0c12b59e0, 0xc0b0f76100, 0x1f, 0x1f, 0x163ad20, 0xc102d2f570, 0xc0ca2dc070, 0xc00e5515b0, 0x1630d60, ...)
        /ext-go/1/src/github.com/klaytn/klaytn/node/cn/api_tracer.go:483 +0x1d7
created by github.com/klaytn/klaytn/node/cn.(*PrivateDebugAPI).traceBlock
        /ext-go/1/src/github.com/klaytn/klaytn/node/cn/api_tracer.go:477 +0x45e
```

**Comment by nogang** [comment] 2020-01-08 20:50
I think it occur because of `debug_traceBlockByNumber - {tracer: "callTracer"}`. 
Shouldn't you call it? I'll fix this problem soon.

**Comment by Jongsic** [comment] 2020-01-14 02:30
I call trace method to trace internal assets(KLAY, KCT) sended action during contract execution.
Is there other way to detect internal sending action?

**Comment by Jongsic** [comment] 2020-01-21 02:02
different type stack trace

```
INFO[01/21,01:56:29 Z] [5] Imported new chain segment                number=18103931 hash=00b42d…bd77e2 blocks=53 txs=3291 elapsed=8.104s       trieDBSize=13.40mB  mgas=470.647 mgasps=58.073
INFO[01/21,01:56:30 Z] [41] Historical state regenerated              block=18103846 elapsed=4.80491136s  nodeSize=6.13mB preimageSize=544.71kB
INFO[01/21,01:56:30 Z] [47] Persisted trie from memory database       updated nodes=48620 updated nodes size=8.52mB time=284.426986ms gcnodes=127763 gcsize=43.81mB gctime=472.756274ms livenodes=4731 livesize=1.64mB
ERROR[01/21,01:56:30 Z] [39] goroutine 3926 [running]:
github.com/klaytn/klaytn/networks/rpc.(*Server).serveRequest.func1(0xc0ac3b8ba0, 0x163e8c0, 0xc1404dfea0)
        /ext-go/1/src/github.com/klaytn/klaytn/networks/rpc/server.go:170 +0x149
panic(0x11fd360, 0x212fe50)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/klaytn/klaytn/blockchain/types.(*Transaction).ValidatedSender(0x0, 0x0, 0x0, 0xc100000000)
        /ext-go/1/src/github.com/klaytn/klaytn/blockchain/types/transaction.go:225 +0x16
github.com/klaytn/klaytn/blockchain.NewEVMContext(0x1645500, 0x0, 0xc14bc20fc0, 0x161ab20, 0xc00f38c800, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /ext-go/1/src/github.com/klaytn/klaytn/blockchain/evm.go:54 +0xe5
github.com/klaytn/klaytn/node/cn.(*PrivateDebugAPI).traceBlock(0xc01204ebb0, 0x1630d60, 0xc14a573500, 0xc132a0d880, 0xc14c6823e0, 0xc14a573500, 0x1630d60, 0xc14a573500, 0xc0bc7e1300, 0x4aecec)
        /ext-go/1/src/github.com/klaytn/klaytn/node/cn/api_tracer.go:502 +0x65d
github.com/klaytn/klaytn/node/cn.(*PrivateDebugAPI).TraceBlockByNumber(0xc01204ebb0, 0x1630d60, 0xc14a573500, 0x1143e7e, 0xc14c6823e0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /ext-go/1/src/github.com/klaytn/klaytn/node/cn/api_tracer.go:365 +0x9d
reflect.Value.call(0xc0ac28dc80, 0xc0ac31cf48, 0x13, 0x13abad6, 0x4, 0xc14a714180, 0x4, 0x4, 0x4, 0x30, ...)
        /usr/local/go/src/reflect/value.go:460 +0x5f6
reflect.Value.Call(0xc0ac28dc80, 0xc0ac31cf48, 0x13, 0xc14a714180, 0x4, 0x4, 0x2, 0x2, 0x11eafe0)
        /usr/local/go/src/reflect/value.go:321 +0xb4
github.com/klaytn/klaytn/networks/rpc.(*Server).handle(0xc0ac3b8ba0, 0x1630d60, 0xc14a573500, 0x163e8c0, 0xc1404dfea0, 0xc14a714120, 0xc1404dff10, 0x0, 0x11eafe0)
        /ext-go/1/src/github.com/klaytn/klaytn/networks/rpc/server.go:400 +0x74e
github.com/klaytn/klaytn/networks/rpc.(*Server).exec(0xc0ac3b8ba0, 0x1630d60, 0xc14a573500, 0x163e8c0, 0xc1404dfea0, 0xc14a714120)
        /ext-go/1/src/github.com/klaytn/klaytn/networks/rpc/server.go:427 +0x1e5
github.com/klaytn/klaytn/networks/rpc.(*Server).serveRequest(0xc0ac3b8ba0, 0x1630e20, 0xc149ede9f0, 0x163e8c0, 0xc1404dfea0, 0xc14b57c001, 0x1, 0x0, 0x0)
        /ext-go/1/src/github.com/klaytn/klaytn/networks/rpc/server.go:254 +0x4f4
github.com/klaytn/klaytn/networks/rpc.(*Server).ServeSingleRequest(...)
        /ext-go/1/src/github.com/klaytn/klaytn/networks/rpc/server.go:296
github.com/klaytn/klaytn/networks/rpc.(*Server).ServeHTTP(0xc0ac3b8ba0, 0x1629920, 0xc149ede900, 0xc13e320800)
        /ext-go/1/src/github.com/klaytn/klaytn/networks/rpc/http.go:219 +0x4b5
github.com/rs/cors.(*Cors).Handler.func1(0x1629920, 0xc149ede900, 0xc13e320800)
        /go/pkg/mod/github.com/rs/cors@v1.4.0/cors.go:200 +0x1af
net/http.HandlerFunc.ServeHTTP(0xc0ac3e0780, 0x1629920, 0xc149ede900, 0xc13e320800)
        /usr/local/go/src/net/http/server.go:2007 +0x44
github.com/klaytn/klaytn/networks/rpc.(*virtualHostHandler).ServeHTTP(0xc0ac3e07a0, 0x1629920, 0xc149ede900, 0xc13e320800)
        /ext-go/1/src/github.com/klaytn/klaytn/networks/rpc/http.go:340 +0x1c1
github.com/valyala/fasthttp/fasthttpadaptor.NewFastHTTPHandler.func1(0xc0bdbd6000)
        /go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/fasthttpadaptor/adaptor.go:85 +0x3e5
github.com/valyala/fasthttp.(*Server).serveConn(0xc0a6a21200, 0x163d660, 0xc14bbe1b80, 0x0, 0x0)
        /go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/server.go:1932 +0x867
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc0a6ab9680, 0xc0c3104340)
        /go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/workerpool.go:212 +0xc0
github.com/valyala/fasthttp.(*workerPool).getCh.func1(0xc0a6ab9680, 0xc0c3104340, 0x114ab60, 0xc0c3104340)
        /go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/workerpool.go:184 +0x35
created by github.com/valyala/fasthttp.(*workerPool).getCh
        /go/pkg/mod/github.com/valyala/fasthttp@v1.2.0/workerpool.go:183 +0x10a
```

**Comment by Jongsic** [comment] 2020-01-21 02:11
When will this problem be solved ?
This problem happens many times on a day, and happens EVERYDAY.

**Comment by KimKyungup** [comment] 2020-02-05 02:47
@Jongsic Sorry for the delay. I am testing with #445 .
The PR prevent the fatal runtime error. 
But I am looking for the root case of this situation. 
So I am running EN with traceBlock call for every block. 
I will solve the problem through it is reproduced.

**Comment by KimKyungup** [comment] 2020-02-13 04:46
@Jongsic I shared the binary with #445. It fixed the issue.
But #445 requires more memory and can make lower performance.
Our team will release next time with more improved PR.
Thanks for the reporting. I close this issue.

**Closed by KimKyungup** 2020-02-13 04:46 UTC
