### ISSUE TITLE
Invalid fee payer and not a program account

### ISSUE THREAD

**Issue by Purnachndar** [klaytn/klaytn#521] opened 2020-05-21 09:38 UTC
**Describe the bug**
Transactions are failing on some extreme cases not all times only two times I am able to find the errors such as invalid fee payer and not a program account 

**Expected behavior**
Hash should get generated

**Attachments**

1. Send Tx failed, launchLog ID: %d, err: %+v 30425 not a program account (e.g., an account having code and storage)
 launcher stop!
panic: not a program account (e.g., an account having code and storage)

2. Send Tx failed, launchLog ID: %d, err: %+v 69624 invalid fee payer
 launcher stop!
panic: invalid fee payer

**Environment (please complete the following information)**
 - Using https://api.cypress.klaytn.net provider
 - go version $ go version 
    go version go1.14.1 darwin/amd64
 - OS and its version [e.g. macOS/10.14]

**Comment by KimKyungup** [comment] 2020-05-22 00:45
@Purnachandar96 Thanks for your reporting. 
I will fix this issue. And I will let you know the progress here.

**Comment by aidan-kwon** [comment] 2020-05-22 02:03
@Purnachandar96 Can I know the more specific situation the problem happened? As you know, Klaytn could operate differently depends on its state. It would be better if you give us the content of the failed transaction and the block number when the transaction tried to be deployed.

Please, check the following things also. 
1. Did you check the contract had successfully deployed (i.e. did you check the receipt of contract deployment tx) before you send the contract execution tx?
2. Did the fee payer has enough KLAY when you send the fee-delegated tx?

**Comment by Purnachandar96** [comment] 2020-05-22 07:09
@aidan-kwon Thanks for the response

Answering to your questions 

1. Yes, Contract is successfully deployed 
2. Yes, It has enough KLAY

**Comment by Purnachandar96** [comment] 2020-05-25 03:59
@KimKyungup @aidan-kwon Hi, Could you suggest me a solution to fix this issue?

**Comment by aidan-kwon** [comment] 2020-05-25 07:37
@Purnachandar96  Currently, we cannot reproduce your errors. As I mentioned earlier, we can investigate deeper if you give us a more detailed explanation. 
- Could we know the whole values of failed transactions (raw transaction or RPC call payload)?
- What was the block number when your transaction failed?
- What time did you try to deploy and fail (in UTC+0)?
- If you were requesting a sequence of RPC call, what were the RPC methods? What was the time interval of the sequence?

**Comment by KimKyungup** [comment] 2021-05-13 23:59
I think this issue can be resolved by increasing `tries-in-memory`.
If someone finds same issue, please report again.

**Closed by KimKyungup** 2021-05-13 23:59 UTC
